# Generated by Django 4.2 on 2024-10-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('alpha2Code', models.CharField(max_length=2, unique=True, verbose_name='Альфа 2 код')),
                ('alpha3Code', models.CharField(max_length=3, unique=True, verbose_name='Альфа 3 код')),
                ('capital', models.CharField(blank=True, max_length=128, null=True, verbose_name='Столица')),
                ('region', models.CharField(blank=True, max_length=64, null=True, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'Страны',
            },
        ),
    ]
