version: '3.10'

services:
  web:
    container_name: web
    build: .
    volumes:
      - ./static:/core/static/
      - ./media:/core/media/
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    env_file:
      - .env
  postgres_db:
    container_name: postgres_db
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres_data:
